modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="poop"
version="2025.04.26"
displayName="goofy ahh mod"
updateJSONURL="https://github.com/gonna-give-you-u/goofy-ahh-mod/releases"
displayURL="https://youtu.be/xvFZjo5PgG0"
logoFile="logo.png"
credits="made in mcreator lol. some of the textures are not mine (except the ones that are crappily drawn), some are public domain"
authors="gonna_give_you_u (ohiofortnite1412)"
description="yes"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.poop]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration